version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:156962844638:task-definition/authorization-ms:7"
        LoadBalancerInfo:
          ContainerName: "authorization-ms"
          ContainerPort: 8081
        PlatformVersion: "LATEST"